/* Local drafts and immutable, public chart annotations. Originals remain unchanged. */
(() => {
'use strict';
const API='https://znlriqmliaszlxlnkeic.supabase.co/functions/v1/fax-drawings';
// Public anonymous API credential; database writes are restricted to the validated server endpoint.
const KEY='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpubHJpcW1saWFzemx4bG5rZWljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTEwMDYyNTIsImV4cCI6MjEwNjU4MjI1Mn0.p9RNJx-6QabOBVm1GeuaY42xFgxNtAyeQeljkowypfY';
const colours=['#df1717','#07952b','#174cf0','#9226bf'],names=['Red','Green','Blue','Purple'],ns='http://www.w3.org/2000/svg';
const bar=document.createElement('div');bar.className='pen-tools';bar.setAttribute('aria-label','Freehand drawing');
bar.innerHTML='<button id="penToggle" aria-pressed="false">✎ Pen</button><span class="pen-colours"></span><button id="penUndo" disabled>Undo</button><button id="penClear" disabled>Clear chart</button><button id="penShare">Share / versions</button><span id="penHint" role="status">Loading shared colours…</span>';
document.querySelector('.toolbar').insertBefore(bar,document.querySelector('#count'));
const $=id=>document.getElementById(id),toggle=$('penToggle'),undo=$('penUndo'),clear=$('penClear'),hint=$('penHint');
const dialog=document.createElement('dialog');dialog.className='sharing-dialog';
dialog.innerHTML='<form method="dialog"><button class="close-share" aria-label="Close sharing">×</button></form><h2>Chart drawings</h2><label>Chart<select id="shareChart"></select></label><label>Displayed version<select id="shareVersion"></select></label><p id="shareStatus" role="status"></p><button id="refreshVersions">Refresh versions</button><button id="withdrawVersion" hidden>Withdraw my published version</button><hr><h3>Publish the displayed lines</h3><label>Public name or nickname<input id="shareName" maxlength="40" autocomplete="nickname" placeholder="Name shown to everyone"></label><p>Publish makes these lines and this name visible to everyone. Names are self-chosen, not verified. Each publication is a separate version; other people cannot change it.</p><button id="publishDrawing">Publish for everyone</button><p>Your unpublished edits stay in this browser. To publish existing desktop drawings, open this page on the browser where you drew them. Withdrawal is available from the publishing browser; clearing browser storage loses that access.</p>';
document.body.append(dialog);
let enabled=false,colour=colours[0],active=null,busy=false,wipe=false,publishing=false;
const frames=new Set(),drafts=new Map(),versions=new Map(),selection=new Map(),pending=new Map(),errors=new Map();
function valid(d){return Array.isArray(d)&&d.length<=200&&d.every(s=>s&&colours.includes(s.colour)&&Array.isArray(s.points)&&s.points.length<=5000&&s.points.every(p=>Array.isArray(p)&&p.length===2&&p.every(n=>Number.isFinite(n)&&n>=0&&n<=20000)));}
function draft(key){if(drafts.has(key))return drafts.get(key);let d=null;try{const raw=localStorage.getItem('fax-freehand:'+key);if(raw&&raw.length<2000000){const parsed=JSON.parse(raw);if(valid(parsed))d=parsed;}}catch{}drafts.set(key,d);return d;}
function shown(key){const sel=selection.get(key);if(sel==='original')return [];if(sel==='draft'||(!sel&&draft(key)!==null))return draft(key)||[];return (versions.get(key)||[]).find(v=>v.id===sel)?.strokes||[];}
function edit(key){if(selection.get(key)!=='draft'){drafts.set(key,structuredClone(shown(key)));selection.set(key,'draft');}if(!drafts.get(key))drafts.set(key,[]);return drafts.get(key);}
function save(key){try{localStorage.setItem('fax-freehand:'+key,JSON.stringify(drafts.get(key)));hint.textContent='Draft saved · use Share to publish';}catch{hint.textContent='Draft kept for this visit only';}}
function prune(){for(const f of frames)if(!f.svg.isConnected)frames.delete(f);if(active&&!active.svg.isConnected)active=null;}
function controls(){prune();toggle.disabled=wipe;toggle.setAttribute('aria-pressed',String(enabled&&!wipe));bar.querySelectorAll('.pen-colours button').forEach(b=>{b.disabled=wipe;b.setAttribute('aria-pressed',String(enabled&&b.dataset.colour===colour&&!wipe));});undo.disabled=clear.disabled=wipe||!active||!shown(active.key).length;$('penShare').disabled=wipe||!active;for(const f of frames)f.svg.classList.toggle('drawing',enabled&&!wipe);}
function line(s){const p=document.createElementNS(ns,'polyline');p.setAttribute('points',s.points.map(p=>p.join(',')).join(' '));p.setAttribute('stroke',s.colour);p.setAttribute('fill','none');p.setAttribute('stroke-width','3');p.setAttribute('stroke-linejoin','round');p.setAttribute('stroke-linecap','round');p.setAttribute('vector-effect','non-scaling-stroke');return p;}
function paint(key){if(busy)return;for(const f of frames)if(f.key===key)f.svg.replaceChildren(...shown(key).map(line));}
function select(f){active=f;controls();hint.textContent=f.label+' · '+(selection.get(f.key)==='draft'?'your local draft':shown(f.key).length?'shared colours':'original chart');}
async function request(method,path='',body){const r=await fetch(API+path,{method,headers:{Authorization:'Bearer '+KEY,apikey:KEY,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(15000)});const d=await r.json();if(!r.ok)throw new Error(d.error||'Sharing unavailable');return d;}
async function fetchVersions(key,force=false){if(pending.has(key))return pending.get(key);if(!force&&versions.has(key))return;const p=(async()=>{try{const rows=await request('GET','?chart='+encodeURIComponent(key));if(!Array.isArray(rows))throw new Error('Invalid response');versions.set(key,rows.filter(v=>typeof v.id==='string'&&typeof v.author==='string'&&valid(v.strokes)));errors.delete(key);if(!selection.has(key))selection.set(key,draft(key)!==null?'draft':versions.get(key)[0]?.id||'original');paint(key);controls();}catch(e){errors.set(key,'Shared colours unavailable. Your draft is safe. Use Refresh versions to retry.');hint.textContent=errors.get(key);}finally{pending.delete(key);if(dialog.open)updateDialog();}})();pending.set(key,p);return p;}
function token(){let t=localStorage.getItem('fax-publisher-token');if(!/^[a-f0-9]{64}$/.test(t||'')){t=Array.from(crypto.getRandomValues(new Uint8Array(32)),b=>b.toString(16).padStart(2,'0')).join('');localStorage.setItem('fax-publisher-token',t);}return t;}
function ownIds(){try{return JSON.parse(localStorage.getItem('fax-published-ids')||'[]');}catch{return [];}}
function updateDialog(){prune();if(!active)return;const choose=$('shareChart');choose.replaceChildren();for(const f of frames){const o=new Option(f.label+' · '+f.caption,f.key);choose.add(o);}choose.value=active.key;const list=$('shareVersion');list.replaceChildren(new Option('Original · no colours','original'));if(draft(active.key)!==null)list.add(new Option('My local draft','draft'));for(const v of versions.get(active.key)||[])list.add(new Option(v.author+' · '+new Date(v.created_at).toLocaleString('en-GB',{timeZone:'UTC'})+' UTC',v.id));list.value=selection.get(active.key)||'original';$('shareStatus').textContent=errors.get(active.key)||(pending.has(active.key)?'Loading versions…':'Published versions are public and tied to this exact chart.');$('withdrawVersion').hidden=!ownIds().includes(list.value);$('publishDrawing').disabled=publishing||!shown(active.key).length;$('refreshVersions').disabled=publishing;choose.disabled=list.disabled=publishing;}
$('penShare').onclick=()=>{if(!active)return;try{$('shareName').value=localStorage.getItem('fax-publisher-name')||'';}catch{}updateDialog();dialog.showModal();fetchVersions(active.key,true);};
$('shareChart').onchange=()=>{const f=[...frames].find(f=>f.key===$('shareChart').value);if(f){select(f);updateDialog();fetchVersions(f.key,true);}};
$('shareVersion').onchange=()=>{if(!active)return;selection.set(active.key,$('shareVersion').value);paint(active.key);select(active);updateDialog();};
$('refreshVersions').onclick=()=>active&&fetchVersions(active.key,true);
$('publishDrawing').onclick=async()=>{if(!active||publishing)return;const f=active,key=f.key,author=$('shareName').value.trim(),strokes=shown(key).map(s=>({colour:s.colour,points:s.points.map(p=>p.map(n=>Math.round(n*10)/10))}));if(!author||author.length>40||/[<>\x00-\x1f]/.test(author)){$('shareStatus').textContent='Enter a name or nickname of 1–40 characters.';return;}publishing=true;updateDialog();$('shareStatus').textContent='Publishing…';try{const t=token();const out=await request('POST','',{token:t,chart:key,author,strokes});try{localStorage.setItem('fax-publisher-name',author);localStorage.setItem('fax-published-ids',JSON.stringify([...ownIds(),out.id]));}catch{}selection.set(key,out.id);await fetchVersions(key,true);hint.textContent='Published · visible on other devices';$('shareStatus').textContent='Published successfully. Other visitors can now load these colours.';}catch(e){$('shareStatus').textContent=e.message||'Could not publish. Your draft is safe.';}finally{publishing=false;$('publishDrawing').disabled=!shown(key).length;$('refreshVersions').disabled=false;$('shareChart').disabled=$('shareVersion').disabled=false;}};
$('withdrawVersion').onclick=async()=>{if(!active||publishing)return;const key=active.key,id=selection.get(key);publishing=true;updateDialog();try{await request('DELETE','',{token:token(),id});selection.delete(key);await fetchVersions(key,true);hint.textContent='Publication withdrawn; your local draft is unchanged';}catch(e){$('shareStatus').textContent=e.message;}finally{publishing=false;updateDialog();}};
toggle.onclick=()=>{enabled=!enabled;controls();hint.textContent=enabled?'Choose a colour and draw · edits stay private until published':'Pen off';};
colours.forEach((c,i)=>{const b=document.createElement('button');b.className='pen-colour';b.dataset.colour=c;b.style.setProperty('--pen-colour',c);b.title=names[i]+' pen';b.setAttribute('aria-label',names[i]+' pen');b.setAttribute('aria-pressed','false');b.onclick=()=>{colour=c;enabled=true;controls();hint.textContent='Draw, then Share to publish';};bar.querySelector('.pen-colours').append(b);});
undo.onclick=()=>{if(!active)return;edit(active.key).pop();paint(active.key);save(active.key);controls();};
clear.onclick=()=>{if(!active)return;drafts.set(active.key,[]);selection.set(active.key,'draft');paint(active.key);save(active.key);controls();};
function attach(c,img,top){if(!img.dataset.penPanel||img.parentElement.querySelector('.pen-layer'))return;const svg=document.createElementNS(ns,'svg');svg.classList.add('pen-layer');svg.setAttribute('viewBox',`0 ${top} ${img.naturalWidth} ${img.naturalHeight-top}`);svg.setAttribute('preserveAspectRatio','none');svg.setAttribute('aria-label','Draw on Chart '+img.dataset.penPanel);const f={svg,key:c.filename,label:'Chart '+img.dataset.penPanel,caption:c.valid_time.slice(5,16).replace('T',' ')+'Z / T+'+c.lead_hours};frames.add(f);img.parentElement.append(svg);draft(f.key);if(!selection.has(f.key)&&draft(f.key)!==null)selection.set(f.key,'draft');paint(f.key);prune();if(!active||f.label==='Chart A')active=f;controls();fetchVersions(f.key);let stroke=null;
const point=e=>{const p=svg.createSVGPoint();p.x=e.clientX;p.y=e.clientY;const q=p.matrixTransform(svg.getScreenCTM().inverse());return [Math.round(Math.max(0,Math.min(img.naturalWidth,q.x))*10)/10,Math.round(Math.max(top,Math.min(img.naturalHeight,q.y))*10)/10];};
img.parentElement.addEventListener('pointerenter',()=>{if(!busy&&!dialog.open)select(f);});
svg.addEventListener('pointerdown',e=>{if(!enabled||wipe||e.button!==0)return;select(f);if(shown(f.key).length>=200){hint.textContent='Maximum 200 lines per chart';return;}edit(f.key);paint(f.key);busy=true;stroke={colour,points:[point(e)]};svg.setPointerCapture(e.pointerId);svg.append(line(stroke));e.preventDefault();});
svg.addEventListener('pointermove',e=>{if(!stroke)return;const p=point(e),last=stroke.points.at(-1);if(Math.hypot(p[0]-last[0],p[1]-last[1])<1.5||stroke.points.length>=5000)return;stroke.points.push(p);svg.lastChild.setAttribute('points',stroke.points.map(p=>p.join(',')).join(' '));});
const finish=(e,cancel=false)=>{if(!stroke)return;if(!cancel){if(stroke.points.length===1)stroke.points.push(point(e));drafts.get(f.key).push(stroke);save(f.key);}stroke=null;busy=false;if(svg.hasPointerCapture(e.pointerId))svg.releasePointerCapture(e.pointerId);paint(f.key);controls();};svg.addEventListener('pointerup',e=>finish(e));svg.addEventListener('pointercancel',e=>finish(e,true));}
window.FaxPen={attach,get busy(){return busy||publishing||dialog.open;},sync(mode){wipe=mode==='wipe';controls();hint.textContent=wipe?'Use 2-up, Single or 4-up for coloured drawings':'Shared colours load automatically · Share to publish';}};
controls();
})();
